name: dmidecode-rs-temp

on:
  push:
    branches:
      - 'jczuluag/integ_tests'
  pull_request:
    branches:
      - 'jczuluag/integ_tests'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
